### ISSUE TITLE
Updating bricker can break it

### ISSUE THREAD

**Issue by arnoldemu** [bblanimation/bricker#31] opened 2019-05-10 10:42 UTC
Hi,
I am using Windows 10. Blender 2.8.

I am sorry but I don't have a reproduction case for this, but a couple of times (once for blender 2.7 and once for blender 2.8) I attempted to update bricker from within blender, but that caused it to stop working.

The only way to solve it was to uninstall and re-install it.

**Comment by bblanimation** [comment] 2019-08-01 01:46
Thank you for reporting this issue! I will assume the issue has been fixed in a round of numerous bug fixes for Bricker v1.7, though due to the broad nature of the bug report there's no way for me to be sure. If you encounter this issue again, please be sure to report it (you can use the "Report Error" button and/or provide a reproduction case). Thanks!

**Closed by bblanimation** 2019-08-01 01:46 UTC
Labels: bug
