### ISSUE TITLE
exportLdraw.py

### ISSUE THREAD

**Issue by mjsweet130** [bblanimation/bricker#38] opened 2019-06-22 22:05 UTC
Please copy the following form and paste it into a new issue at https://github.com/bblanimation/bricker/issues

Don't forget to include a description of your problem! The more information you provide (what you were trying to do, what action directly preceeded the error, etc.), the easier it will be for us to squash the bug.

### COPY EVERYTHING BELOW THIS LINE ###

Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1, 6, 3
Platform Info:
   system   = Darwin
   platform = Darwin-18.6.0-x86_64-i386-64bit
   version  = Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
   python   = 3.5.3
Error:
EXCEPTION (<class 'AttributeError'>): 'str' object has no attribute 'name'
         /Users/msweet/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-6-3/buttons/exportLdraw.py
000 0112:writeLdrawFile() mat_name = "" if mat is None else mat.name
001 0048:execute() self.writeLdrawFile()

**Comment by bblanimation** [comment] 2019-07-12 01:38
Duplicate of issue #40

**Closed by bblanimation** 2019-07-12 01:38 UTC
