### ISSUE TITLE
Cannot export ldraw

### ISSUE THREAD

**Issue by MoeAllen** [bblanimation/bricker#40] opened 2019-06-30 02:24 UTC
Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1, 6, 3
Platform Info:
   system   = Darwin
   platform = Darwin-18.6.0-x86_64-i386-64bit
   version  = Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
   python   = 3.5.3
Error:
EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'keys'
         /Users/maryallen/Library/Application Support/Blender/2.79/scripts/addons/bricker_v1-6-3/buttons/exportLdraw.py
000 0077:writeLdrawFile() offset = vec_conv(bricksDict[list(bricksDict.keys())[0]]["co"], int)
001 0048:execute() self.writeLdrawFile()

**Comment by bblanimation** [comment] 2019-07-12 01:38
Duplicate of issue #37

**Closed by bblanimation** 2019-07-12 01:38 UTC
