### ISSUE TITLE
Failure when trying to export to LDraw

### ISSUE THREAD

**Issue by legofreak133** [bblanimation/bricker#37] opened 2019-06-19 23:48 UTC
Blender Version: 002.079.000
Addon Version: 1, 6, 3
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763
   version  = 10.0.17763
   python   = 3.5.3
Error:
EXCEPTION (<class 'AttributeError'>): module 'bpy.props' has no attribute 'abs_mat_properties'
         C:\Users\Hannah Arnold\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-6-3\functions\colors.py
000 0030:getColors() mat_properties = bpy.props.abs_mat_properties
001 0040:findNearestBrickColorName() colors = getColors().copy()
         C:\Users\Hannah Arnold\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bricker_v1-6-3\buttons\exportLdraw.py
002 0118:writeLdrawFile() mat_name = findNearestBrickColorName(rgba, transWeight)
003 0048:execute() self.writeLdrawFile()

**Comment by bblanimation** [comment] 2019-07-12 01:40
Thank you for reporting this issue! This has been fixed for the next release of Bricker (expect it when the official release of Blender 2.80 is published!)
duplicate of issue #24

**Closed by bblanimation** 2019-07-12 01:40 UTC
