### ISSUE TITLE
Export Ldraw broken

### ISSUE THREAD

**Issue by Senorpablo** [bblanimation/bricker#41] opened 2019-07-23 02:07 UTC
Description of the Problem:

Blender Version: 002.080.074
Addon Version: 1, 6, 3
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.16299
   version  = 10.0.16299
   python   = 3.7.0
Error:
EXCEPTION (<class 'AttributeError'>): module 'bpy.props' has no attribute 'abs_mat_properties'
         C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\bricker_v1-6-3\functions\colors.py
000 0030:getColors() mat_properties = bpy.props.abs_mat_properties
001 0040:findNearestBrickColorName() colors = getColors().copy()
         C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\bricker_v1-6-3\buttons\exportLdraw.py
002 0118:writeLdrawFile() mat_name = findNearestBrickColorName(rgba, transWeight)
003 0048:execute() self.writeLdrawFile()

**Comment by bblanimation** [comment] 2019-07-24 00:56
Thank you for reporting this issue! This has been fixed for the next release of Bricker and you can expect it released soon after the official release of Blender 2.80. (duplicate of issue #37)

**Closed by bblanimation** 2019-07-24 00:56 UTC
Labels: bug, fixed
